enable-receivers: false

et-service:
  image:
    tag: "5.23.1"
  autoscaling:
    enabled: false

et-collector:
  image:
    tag: "5.23.0"
  autoscaling:
    enabled: false

et-receiver-agent:
  et:
    redisQueue:
      type: agent
  image:
    tag: "5.23.1"

et-receiver-decompile:
  et:
    redisQueue:
      type: decompile
  image:
    tag: "5.23.1"

et-receiver-hit:
  et:
    redisQueue:
      type: hit
  image:
    tag: "5.23.1"

et-receiver-sql:
  et:
    redisQueue:
      type: sql
  image:
    tag: "5.23.1"